color: null
fieldLayouts:
  21033e2b-4b12-45df-9ab2-9caaaf90a544:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d37923f-ba15-4c43-aae8-a99293969a38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cda95c2d-ef11-4099-a72b-d5221eec3054 # Hero image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98e519cf-1298-4bdf-a358-a99f215f5a76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d8e5a63-b933-48f1-bc47-36b9232c0cbb # Hero subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a066bae-cab8-4b9a-b195-afad2181a70b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: daa4d7a8-f064-4e0f-8da1-1666dd541e6a # Hero Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37ac2f36-ee48-4ae9-8b83-c32dce900036
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ca78839-9ac9-4dfd-abcc-e798e8dfb86d
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
