color: null
fieldLayouts:
  b969c454-d8fa-44d8-8890-e6ebb3b8ab7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f29a11bd-fbd3-4a8e-8d16-3d0d034bb29c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 437f8a5a-f93e-405c-880f-f23a10c8d249
        userCondition: null
handle: productPage
hasTitleField: true
icon: ''
name: 'product page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
