altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  430a78d4-141d-4b56-8058-fd854ac9b43b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ff66d75f-f1ec-423b-aba2-5fd86602161c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b018fdc-23cb-4fea-9041-bf0ce2eb68c0
        userCondition: null
fs: uploads
handle: uploads
name: uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
