dateModified: 1715859014
email:
  fromEmail: lboonen02@gmail.com
  fromName: mangastore
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    788d2973-ee04-4ffb-900f-93e20798fdfb: mangastore # mangastore
    f0fcd4fa-846c-4975-a821-f3c45e4e10ba: mangastore # mangastore
system:
  edition: pro
  live: true
  name: mangastore
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
