defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5d98e6b8-7fd0-4a5e-920a-912fcfe7fb07 # contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  788d2973-ee04-4ffb-900f-93e20798fdfb: # mangastore
    enabledByDefault: true
    hasUrls: true
    template: contact
    uriFormat: contact
type: single
