defaultPlacement: end
enableVersioning: true
entryTypes:
  - 58849cb1-9acd-4eba-b919-21db1172dc3c # Home
handle: home
maxAuthors: 1
name: home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  788d2973-ee04-4ffb-900f-93e20798fdfb: # mangastore
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
