defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7cbccd2e-9cef-4e0f-8855-908a8bd2321c # product
handle: product
maxAuthors: 1
name: product
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  788d2973-ee04-4ffb-900f-93e20798fdfb: # mangastore
    enabledByDefault: true
    hasUrls: true
    template: product/_entry
    uriFormat: 'product/{slug}'
type: channel
